use COFFEE
CREATE TABLE TAIKHOAN(
    MATK VARCHAR(10) NOT NULL PRIMARY KEY,
    TENDANGNHAP VARCHAR(255),
    MATKHAU VARCHAR(500),
    LOAITAIKHOAN BIT  -- 1 LA CUA ADMIN, 0 LA CUA NHAN VIEN
)
CREATE TABLE BAN(
    MA_BAN VARCHAR(10) NOT NULL PRIMARY KEY,
    TENBAN NVARCHAR(50),
    TRANGTHAI BIT  DEFAULT 0-- 0 LA TRONG, KHAC 0 LA DA CO KHACH
)

CREATE TABLE MON(
    MaMON VARCHAR(10) NOT NULL PRIMARY KEY,
    TENMON NVARCHAR(255),
    GIA FLOAT,
    LOAI VARCHAR(10),
    MOTA NVARCHAR(255),
    TRANGTHAI BIT
)

CREATE TABLE NHANVIEN(
    MANV VARCHAR(10) NOT NULL PRIMARY KEY,
    MATK VARCHAR(10) FOREIGN KEY REFERENCES TAIKHOAN(MATK),
    TENNV NVARCHAR(255),
    DIACHI NVARCHAR(255),
    DIENTHOAI VARCHAR(11),
    CCCD VARCHAR(15)
)

CREATE TABLE HOADON(
    MaHOADON VARCHAR(10) NOT NULL PRIMARY KEY,
    MA_NV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
    MA_BAN VARCHAR(10) FOREIGN KEY REFERENCES BAN(MA_BAN),
    GHICHU NVARCHAR(255),
    THODIEMVAO DATE DEFAULT GETDATE()
)
CREATE TABLE  CHI_TIET_HD(
    MA_HOADON VARCHAR(10) FOREIGN KEY REFERENCES HOADON(MaHOADON),
    MA_MON VARCHAR(10) FOREIGN KEY REFERENCES MON(MaMON),
    SOLUONG INT,
    GHICHU NVARCHAR(255),
    PRIMARY KEY (MA_HOADON, MA_MON)
)
 CREATE TABLE GIAODICH(
     MAGIAODICH VARCHAR(10) NOT NULL PRIMARY KEY,
     MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV),
     MAHOADON VARCHAR(10),
     MA_MON VARCHAR(10),
     THOIDIEMVAO DATE,
     THOIDIEMRA DATE DEFAULT GETDATE(),
     TRANGTHAI BIT,
     TONGTIEN FLOAT,
     FOREIGN KEY (MAHOADON, MA_MON) REFERENCES CHI_TIET_HD
 )
